spring:
  application:
    name: ${SERVER_NAME}

  data:
    mongodb:
      uri: ${URI}
      database: ${DATABASE_NAME}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASS}

server:
  port: ${SERVER_PORT}

jwt:
  secretKey: ${SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG