spring:
  application:
    name: ${SERVER_NAME}

  data:
    mongodb:
      uri: ${URI}
      database: ${DATABASE_NAME}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASS}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

server:
  port: ${SERVER_PORT}

jwt:
  secretKey: ${SECRET_KEY}

frontend:
  url: ${FRONTEND_URL}
logging:
  level:
    org.springframework.security: DEBUG