spring:
  application:
    name: ${SERVER_NAME}

  data:
    mongodb:
      uri: ${URI}
      database: ${DATABASE_NAME}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT}

jwt:
  secretKey: ${SECRET_KEY}

auth:
  userService:
    url: ${AUTH_SERVER_URL}
  internalSharedKey: ${INTERNAL_SHARED_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

